
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class FullNavigation extends Simulation {

	val httpProtocol = http
		.baseURL("http://localhost:8080")
		.inferHtmlResources()
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3")
		.userAgentHeader("Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0")

	val headers_0 = Map("Upgrade-Insecure-Requests" -> "1")



	val scn = scenario("RecordedSimulation")
		.exec(http("request_0")
			.post("/login")
			.headers(headers_0)
			.formParam("username", "calleja@email.com")
			.formParam("password", "password"))
		.pause(14)
		.exec(http("request_1")
			.get("/user/voteProposal/1")
			.headers(headers_0))
		.pause(2)
		.exec(http("request_2")
			.get("/user/viewProposal/2")
			.headers(headers_0))
		.pause(4)
		.exec(http("request_3")
			.get("/user/orderCommentsDate/2")
			.headers(headers_0))
		.pause(2)
		.exec(http("request_4")
			.get("/user/orderCommentsPopularity/2")
			.headers(headers_0))
		.pause(6)
		.exec(http("request_5")
			.get("/user/voteComment/5")
			.headers(headers_0))
		.pause(20)
		.exec(http("request_6")
			.post("/user/commentProposal/2")
			.headers(headers_0)
			.formParam("comment", "It's a good idea"))
		.pause(3)
		.exec(http("request_7")
			.get("/user/home")
			.headers(headers_0))
		.pause(4)
		.exec(http("request_8")
			.get("/user/addForm/")
			.headers(headers_0))
		.pause(28)
		.exec(http("request_9")
			.post("/user/addProposal")
			.headers(headers_0)
			.formParam("category", "2")
			.formParam("text", "ComicCon"))
		.pause(6)
		.exec(http("request_10")
			.get("/participants/userInfo")
			.headers(headers_0))
		.pause(9)
		.exec(http("request_11")
			.post("/participants/changePassword")
			.headers(headers_0)
			.formParam("password", "password")
			.formParam("email", "calleja@email.com")
			.formParam("firstName", "Pepe")
			.formParam("lastName", "Calleja")
			.formParam("birthDate", "1950-03-25 00:00:00.0")
			.formParam("nationality", "Spanish")
			.formParam("address", "Oviedo")
			.formParam("dni", "12345678A"))
		.pause(10)
		.exec(http("request_12")
			.post("/participants/update")
			.headers(headers_0)
			.formParam("email", "calleja@email.com")
			.formParam("password", "password")
			.formParam("oldPassword", "password"))
		.pause(2)
		.exec(http("request_13")
			.post("/participants/update")
			.headers(headers_0)
			.formParam("email", "calleja@email.com")
			.formParam("firstName", "Pepe")
			.formParam("lastName", "Calleja")
			.formParam("nationality", "Spanish")
			.formParam("address", "Oviedo")
			.formParam("dni", "12345678A"))
		.pause(7)
		.exec(http("request_14")
			.get("/participants/userInfo")
			.headers(headers_0))
		.pause(1)
		.exec(http("request_15")
			.get("/user/home")
			.headers(headers_0))
		.pause(2)
		.exec(http("request_16")
			.get("/logout")
			.headers(headers_0))

	setUp(scn.inject(rampUsers(30) over(60 seconds))).protocols(httpProtocol)
}